[package]
name = "biofilm"
version = "0.1.0"
edition = "2021"

[lib]
name = "biofilm_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.2", features = ["extension-module", "abi3-py38"] }
numpy = "0.28.0"
